{{- if and .Values.cnpg.enabled .Values.singleTenant.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "rask.fullname" . }}-postgres
  labels:
    {{- include "rask.componentLabels" (list . "postgres") | nindent 4 }}
spec:
  instances: {{ .Values.cnpg.instances }}
  imageName: {{ .Values.cnpg.imageName | quote }}
  bootstrap:
    initdb:
      database: {{ .Values.cnpg.database | quote }}
      owner: {{ .Values.cnpg.user | quote }}
      secret:
        name: {{ include "rask.fullname" . }}-postgres
  storage:
    size: {{ .Values.cnpg.storage | quote }}
    storageClass: {{ .Values.cnpg.storageClass | quote }}
  resources:
    {{- toYaml .Values.cnpg.resources | nindent 4 }}
{{- end }}
