apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rask.fullname" . }}-config
  labels:
    {{- include "rask.labels" . | nindent 4 }}
data:
  {{- range $k, $v := .Values.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
  RASK_API_PREFIX: "/api/v1"
