apiVersion: v1
kind: Service
metadata:
  name: {{ include "rask.fullname" . }}-frontend
  labels:
    {{- include "rask.componentLabels" (list . "frontend") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: http
  selector:
    {{- include "rask.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
