{{- if .Values.migrations.enabled }}
{{- $secretName := .Values.existingSecret | default (printf "%s-app" (include "rask.fullname" .)) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "rask.fullname" . }}-migrate
  labels:
    {{- include "rask.componentLabels" (list . "migrate") | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        {{- include "rask.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rask.serviceAccountName" . }}
      {{- if .Values.cnpg.enabled }}
      initContainers:
        - name: wait-postgres
          image: busybox:1.36
          command: ["sh","-c","until nc -z {{ include "rask.fullname" . }}-postgres-rw {{ .Values.cnpg.port }}; do echo waiting postgres; sleep 2; done"]
      {{- end }}
      containers:
        - name: migrate
          image: "{{ .Values.image.repository }}{{ if .Values.image.repository }}/{{ end }}core-api:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.migrations.command | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "rask.fullname" . }}-config
            - secretRef:
                name: {{ $secretName }}
          resources:
            {{- toYaml .Values.migrations.resources | nindent 12 }}
{{- end }}
