{{- if .Values.observability.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rask.fullname" . }}-observability-s3
  labels:
    {{- include "rask.componentLabels" (list . "observability") | nindent 4 }}
type: Opaque
stringData:
  GREPTIMEDB_STANDALONE__STORAGE__ACCESS_KEY_ID: {{ include "rask.minioAccessKey" . | quote }}
  GREPTIMEDB_STANDALONE__STORAGE__SECRET_ACCESS_KEY: {{ include "rask.minioSecretKey" . | quote }}
{{- end }}
