apiVersion: v1
kind: Service
metadata:
  name: {{ include "rask.fullname" . }}-viewer
  labels:
    {{- include "rask.labels" . | nindent 4 }}
    app.kubernetes.io/component: viewer
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.viewer.service.port }}
      targetPort: http
  selector:
    {{- include "rask.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: viewer
