apiVersion: v2
name: ra-hcp
description: FastAPI backend and SvelteKit frontend for HCP S3 data-plane and Management API (MAPI) operations
type: application
version: 0.3.0
appVersion: "v0.1.1"
home: https://github.com/AI-Riksarkivet/ra-hcp
sources:
  - https://github.com/AI-Riksarkivet/ra-hcp
maintainers:
  - name: ra-hcp-team
