[project]
name = "ray-api-project"
version = "0.1.0"
description = "Deployable: ray-api service."
requires-python = ">=3.13"
dependencies = ["ray-api"]

[tool.uv.sources]
ray-api = { workspace = true }
ray-kit = { workspace = true }
service-kit = { workspace = true }

[tool.uv.workspace]
members = [
    "../../components/services/ray_api",
    "../../packages/ray-kit",
    "../../packages/service-kit",
]
