#!/usr/bin/env bash
# A Dagger engine that can push to the plain-HTTP dev registry.
#
# WHY THIS EXISTS. Dagger always speaks HTTPS to a registry and `publish` has no `--insecure` flag, so
# against the `rask-registry` container (registry:2 on :5000, no TLS) every push dies with:
#
#   failed to do request: Head "https://172.17.0.1:5000/v2/…":
#   http: server gave HTTP response to HTTPS client
#
# The only lever is the engine's own BuildKit config, and the stock engine Dagger auto-provisions has no
# way to receive one. So we run our OWN engine container with an engine.toml mounted, and point the CLI
# at it via _EXPERIMENTAL_DAGGER_RUNNER_HOST.
#
# ADDRESS THE REGISTRY AS 172.17.0.1:5000, NOT localhost:5000. The engine is a container: `localhost`
# inside it is the engine itself, so a push to localhost:5000 fails with connection refused while looking
# exactly like a registry problem. 172.17.0.1 is the docker bridge gateway — the host, from a container.
#
# Idempotent. Re-run after a Dagger CLI upgrade: the engine image is pinned to the CLI's version below
# and a mismatch makes the CLI provision its own (config-less) engine instead, silently reverting to the
# HTTPS failure above.
set -euo pipefail

NAME="${DAGGER_ENGINE_NAME:-dagger-engine-rask}"
REGISTRY_HOST="${DAGGER_REGISTRY_HOST:-172.17.0.1:5000}"

# Pin the engine to the CLI's own version — Dagger refuses a mismatched pair.
VERSION="$(dagger version 2>/dev/null | awk '{print $2}')"
if [[ -z "$VERSION" ]]; then
  echo "!! dagger CLI not found on PATH — https://docs.dagger.io/install" >&2
  exit 1
fi

CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/dagger"
mkdir -p "$CONF_DIR"
cat > "$CONF_DIR/engine.toml" <<EOF
# Generated by scripts/dagger-engine.sh — the dev registry is plain HTTP.
[registry."${REGISTRY_HOST}"]
  http = true
EOF

if [[ "$(docker inspect -f '{{.State.Running}}' "$NAME" 2>/dev/null || echo false)" == "true" ]]; then
  running_image="$(docker inspect -f '{{.Config.Image}}' "$NAME")"
  if [[ "$running_image" == *"$VERSION" ]]; then
    echo ">> $NAME already running on $VERSION"
    echo ">> export _EXPERIMENTAL_DAGGER_RUNNER_HOST=docker-container://$NAME"
    exit 0
  fi
  echo ">> $NAME runs $running_image but the CLI is $VERSION — recreating"
fi

docker rm -f "$NAME" >/dev/null 2>&1 || true
docker run -d --restart=unless-stopped --privileged --name "$NAME" \
  -v "dagger-engine-rask-state:/var/lib/dagger" \
  -v "$CONF_DIR/engine.toml:/etc/dagger/engine.toml:ro" \
  "registry.dagger.io/engine:$VERSION" --config /etc/dagger/engine.toml >/dev/null

echo ">> $NAME started ($VERSION), ${REGISTRY_HOST} marked insecure"
echo ">> export _EXPERIMENTAL_DAGGER_RUNNER_HOST=docker-container://$NAME"
