#!/usr/bin/env bash
# A Dagger engine that can push to the plain-HTTP dev registry.
#
# WHY THIS EXISTS. Dagger always speaks HTTPS to a registry and `publish` has no `--insecure` flag, so
# against the `rask-registry` container (registry:2 on :5000, no TLS) every push dies with:
#
#   failed to do request: Head "https://172.17.0.1:5000/v2/…":
#   http: server gave HTTP response to HTTPS client
#
# The only lever is the engine's own BuildKit config, and the stock engine Dagger auto-provisions has no
# way to receive one. So we run our OWN engine container with an engine.toml mounted, and point the CLI
# at it via _EXPERIMENTAL_DAGGER_RUNNER_HOST.
#
# ADDRESS THE REGISTRY AS 172.17.0.1:5000, NOT localhost:5000. The engine is a container: `localhost`
# inside it is the engine itself, so a push to localhost:5000 fails with connection refused while looking
# exactly like a registry problem. 172.17.0.1 is the docker bridge gateway — the host, from a container.
#
# Idempotent. Re-run after a Dagger CLI upgrade: the engine image is pinned to the CLI's version below
# and a mismatch makes the CLI provision its own (config-less) engine instead, silently reverting to the
# HTTPS failure above.
set -euo pipefail

NAME="${DAGGER_ENGINE_NAME:-dagger-engine-rask}"
REGISTRY_HOST="${DAGGER_REGISTRY_HOST:-172.17.0.1:5000}"

# Cache ceiling. See the engine.toml comment below for why an explicit one is needed.
MAX_USED_SPACE="${DAGGER_MAX_USED_SPACE:-60GB}"
MIN_FREE_SPACE="${DAGGER_MIN_FREE_SPACE:-100GB}"
RESERVED_SPACE="${DAGGER_RESERVED_SPACE:-10GB}"

# Pin the engine to the CLI's own version — Dagger refuses a mismatched pair.
VERSION="$(dagger version 2>/dev/null | awk '{print $2}')"
if [[ -z "$VERSION" ]]; then
  echo "!! dagger CLI not found on PATH — https://docs.dagger.io/install" >&2
  exit 1
fi

CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/dagger"
mkdir -p "$CONF_DIR"
cat > "$CONF_DIR/engine.toml" <<EOF
# Generated by scripts/dagger-engine.sh — the dev registry is plain HTTP.
[registry."${REGISTRY_HOST}"]
  http = true

# BOUND THE CACHE. Dagger's default GC policy is proportional to the disk, so on a large volume it is
# enormous — measured on a 7.4 TB disk: maxUsedSpace 5.67 TB, minFreeSpace 1.51 TB. The engine therefore
# never collected, and dagger-engine-rask-state grew to 1.126 TB of BuildKit cache before anyone noticed
# (\`docker system df -v\`). Nothing was wrong with Dagger; the default is simply sized for the disk and
# not for what this repo needs.
#
# A cap in the tens of GB keeps every layer that matters — the fleet's uv sync and the zones' bun install
# are the expensive ones and they are a few GB together — while making unbounded growth impossible.
# Tune with DAGGER_MAX_USED_SPACE if a machine wants a different ceiling.
[worker.oci]
  maxUsedSpace = "${MAX_USED_SPACE}"
  minFreeSpace = "${MIN_FREE_SPACE}"
  reservedSpace = "${RESERVED_SPACE}"
EOF

if [[ "$(docker inspect -f '{{.State.Running}}' "$NAME" 2>/dev/null || echo false)" == "true" ]]; then
  running_image="$(docker inspect -f '{{.Config.Image}}' "$NAME")"
  # Version AND config must both match. Checking only the version meant a changed engine.toml — a new
  # registry, or the GC ceiling that stops the cache reaching a terabyte — was written to disk and then
  # never applied, because the running engine was "already on the right version". The config is mounted
  # read-only, so the only way to apply a change is to recreate the container.
  if [[ "$running_image" == *"$VERSION" ]] \
     && docker exec "$NAME" cat /etc/dagger/engine.toml 2>/dev/null | diff -q - "$CONF_DIR/engine.toml" >/dev/null 2>&1; then
    echo ">> $NAME already running on $VERSION with the current config"
    echo ">> export _EXPERIMENTAL_DAGGER_RUNNER_HOST=docker-container://$NAME"
    exit 0
  fi
  echo ">> $NAME runs $running_image but the CLI is $VERSION — recreating"
fi

docker rm -f "$NAME" >/dev/null 2>&1 || true
docker run -d --restart=unless-stopped --privileged --name "$NAME" \
  -v "dagger-engine-rask-state:/var/lib/dagger" \
  -v "$CONF_DIR/engine.toml:/etc/dagger/engine.toml:ro" \
  "registry.dagger.io/engine:$VERSION" --config /etc/dagger/engine.toml >/dev/null

echo ">> $NAME started ($VERSION), ${REGISTRY_HOST} marked insecure"
echo ">> export _EXPERIMENTAL_DAGGER_RUNNER_HOST=docker-container://$NAME"
