#!/usr/bin/env bash
# Write a values file pinning EVERY image to what the cluster is actually running (#135).
#
# The chart has one `image.tag`, and this fleet has never been one tag: a catalog tag across 11
# services, a different tag on gateway/compute/controlplane, a third across the 7 zones, and an
# ingest DIGEST. Rendering all of them from one value is what made `helm upgrade` destructive —
# every image rewritten to a tag the node does not hold, whole fleet ImagePullBackOff, recovered by
# hand. Measured twice on 2026-08-06.
#
# So: read the truth out of the cluster and hand it to helm. `helm upgrade -f <this>` then changes
# only what you meant to change. It is a CAPTURE, not a source of truth — the fix for a stale pin is
# to rebuild that image and re-run this, never to hand-edit the file.
set -euo pipefail
KUBECONFIG="${KUBECONFIG:-/etc/rancher/k3s/k3s.yaml}"
OUT="${1:-chart/values-live-pins.yaml}"
KUBECTL="${KUBECTL:-kubectl}"

"$KUBECTL" get deploy,statefulset -o json | python3 -c '
import json, sys

tags, digests = {}, {}
# component -> {tag_or_digest: [workloads running it]}. The chart has ONE tag per image stem, so a stem
# running two different tags cannot be represented in the output at all — see the guard below.
sources = {}
for item in json.load(sys.stdin)["items"]:
    owner = item["metadata"]["name"]
    for c in item["spec"]["template"]["spec"].get("containers", []):
        ref = c["image"]
        # FIRST-PARTY ONLY. `image.tags` feeds `rask.image`, which renders only the images this repo
        # builds; dex, greptimedb, cloudnative-pg and friends come from their own values and pinning
        # them here would be noise that looks authoritative. The test is the registry host: a
        # third-party ref names a real one (docker.io, ghcr.io, quay.io — anything with a dot), ours
        # is either bare (side-loaded) or the local registry.
        head = ref.split("/", 1)[0] if "/" in ref else ""
        if "." in head and not head.startswith("localhost") and not head.startswith("172."):
            continue
        # Strip the registry: the chart supplies it from image.repository, and a pin that carried it
        # would fight that value instead of complementing it.
        name = ref.rsplit("/", 1)[-1]
        if "@" in name:
            component, digest = name.split("@", 1)
            digests[component] = digest
            sources.setdefault(component, {}).setdefault("@" + digest, []).append(owner)
        elif ":" in name:
            component, tag = name.rsplit(":", 1)
            tags[component] = tag
            sources.setdefault(component, {}).setdefault(tag, []).append(owner)

# REFUSE rather than guess. `tags[component] = tag` is keyed by image STEM, and eleven workloads share
# the `lance-rest-catalog` stem here. When one of them runs a different tag — the normal result of a
# `kubectl set image` on a single deployment — the assignment above is LAST-WRITER-WINS by dict
# iteration order, and the losing tag vanishes from a file whose whole promise is "what the cluster is
# actually RUNNING". The next `make k3s-up` then reverts that workload with nothing reporting it.
# MEASURED 2026-08-16: rask-maintenance ran `maint-0517356a` (two shipped fixes) while its ten stem-mates
# ran `main-d7d75cf0`; the generated file recorded only the latter, so an upgrade would have silently
# rolled the fixes back. There is no honest pin to emit in that state, so this exits instead — the
# resolution is to build ONE image carrying every change and roll the whole stem, not to hand-edit.
split = {c: v for c, v in sorted(sources.items()) if len(v) > 1}
if split:
    sys.stderr.write("ERROR: these image stems run MORE THAN ONE tag; the chart has one tag per stem,\n")
    sys.stderr.write("so no correct pin file exists until they converge:\n\n")
    for component, by_tag in split.items():
        sys.stderr.write("  " + component + "\n")
        for tag, owners in sorted(by_tag.items()):
            sys.stderr.write("    " + tag + "  <- " + ", ".join(sorted(owners)) + "\n")
    sys.stderr.write("\nRebuild one image from a commit carrying every change, roll the whole stem, re-run.\n")
    sys.exit(1)

def block(label, mapping):
    if not mapping:
        return f"  {label}: {{}}\n"
    lines = "".join(f"    {k}: {json.dumps(v)}\n" for k, v in sorted(mapping.items()))
    return f"  {label}:\n{lines}"

sys.stdout.write(
    "# GENERATED by scripts/k3s-pins.sh — what the cluster is RUNNING, not what anyone intended.\n"
    "# Regenerate after every build+roll; never hand-edit. See #135.\n"
    "image:\n" + block("tags", tags) + block("digests", digests)
)
' > "$OUT"

echo ">> wrote $OUT"
grep -c ':' "$OUT" || true
