import { describe, expect, it, vi } from 'vitest';

// `$env/dynamic/private` is generated by SvelteKit and does not exist under a bare vitest run, so it
// is stubbed here. The stub is also what lets the upstream base be asserted: the handler reads
// CATALOG_API at module scope, so the value below IS the target these tests check for.
vi.mock('$env/dynamic/private', () => ({ env: { CATALOG_API: 'http://catalog.test:2333' } }));

const { POST } = await import('./+server');

type Locals = { authEnabled?: boolean; session?: { accessToken: string } | null };

/** Drive the handler with a recording `fetch`, returning the response and what reached the upstream. */
async function call(opts: {
	body?: unknown;
	locals?: Locals;
	upstream?: (url: string, init: RequestInit) => Response | Promise<Response>;
}) {
	const seen: { url: string; init: RequestInit }[] = [];
	const fetchImpl = async (url: string, init: RequestInit) => {
		seen.push({ url, init });
		return opts.upstream
			? await opts.upstream(url, init)
			: new Response(new Uint8Array([1, 2, 3]), {
					status: 200,
					headers: { 'content-type': 'application/vnd.apache.arrow.file' },
				});
	};
	const request = new Request('http://zone.test/capi/v1/table/t1/query', {
		method: 'POST',
		body: opts.body === undefined ? undefined : JSON.stringify(opts.body),
	});
	const response = await (POST as unknown as (e: unknown) => Promise<Response>)({
		params: { id: 'acme-silver$features' },
		request,
		fetch: fetchImpl,
		locals: opts.locals ?? {},
	});
	return { response, seen };
}

const bodyOf = (init: RequestInit) => JSON.parse(String(init.body)) as Record<string, unknown>;

/** The single upstream call, asserted rather than optional-chained — if the handler never called out,
 *  that is the failure to report, not a `TypeError` three lines later. */
function only(seen: { url: string; init: RequestInit }[]) {
	if (seen.length !== 1) throw new Error(`expected exactly one upstream call, got ${seen.length}`);
	return seen[0] as { url: string; init: RequestInit };
}

const headersOf = (call: { init: RequestInit }) => call.init.headers as Record<string, string>;

describe('the table-preview proxy', () => {
	// Every assertion here was absent, and the file was mutation-proved unguarded: replacing BOTH
	// handler bodies with a 500 — no auth gate, no clamp, no bearer, no upstream call — left the three
	// specs that name this contract 54/54 GREEN, because each intercepts the route at `page.route`.
	// A route mocked by every spec that mentions it is a route nothing tests.

	it('refuses an anonymous request when auth is on, and does not reach the catalog', async () => {
		const { response, seen } = await call({ locals: { authEnabled: true, session: null } });

		expect(response.status).toBe(401);
		expect(seen, 'a 401 must be decided here, not by the upstream').toEqual([]);
	});

	it('serves an auth-off stack without a bearer', async () => {
		// `dev-zone` and every hermetic zone suite run auth-off; a gate keyed on session alone would
		// make the preview unreachable there while looking correct in prod.
		const { response, seen } = await call({ locals: { authEnabled: false } });

		expect(response.status).toBe(200);
		expect(seen).toHaveLength(1);
		expect(only(seen).init.headers).not.toHaveProperty('authorization');
	});

	it('forwards the signed-in bearer and nothing else', async () => {
		const { seen } = await call({
			locals: { authEnabled: true, session: { accessToken: 'tok-abc' } },
		});

		expect(headersOf(only(seen))['authorization']).toBe('Bearer tok-abc');
	});

	it('builds the catalog body ITSELF — a client cannot smuggle a query shape through', async () => {
		// The confused-deputy property, and the reason this route is narrow: the browser sends only a
		// row budget. Everything else in its payload must be discarded, because this proxy attaches the
		// caller's session bearer and a forwarded `filter`/`columns`/`vector` would run under it.
		const { seen } = await call({
			body: {
				limit: 10,
				vector: { embedding: [0.1, 0.2] },
				filter: "tenant = 'other'",
				columns: ['secret'],
				k: 9999,
			},
		});

		expect(bodyOf(only(seen).init)).toEqual({ k: 10, vector: {} });
	});

	it.each([
		['above the cap', 100_000, 500],
		['at the cap', 500, 500],
		['below the floor', 0, 1],
		['negative', -5, 1],
		['fractional', 12.7, 12],
	])('clamps a limit %s: %d -> %d', async (_label, limit, expected) => {
		const { seen } = await call({ body: { limit } });
		expect(bodyOf(only(seen).init).k).toBe(expected);
	});

	it.each([
		['no body', undefined],
		['a non-numeric limit', { limit: 'all' }],
		['NaN', { limit: Number.NaN }],
		['Infinity', { limit: Number.POSITIVE_INFINITY }],
	])('falls back to the default preview size for %s', async (_label, body) => {
		const { seen } = await call({ body });
		expect(bodyOf(only(seen).init).k).toBe(50);
	});

	it('targets the catalog query route with the table id encoded', async () => {
		const { seen } = await call({});
		expect(only(seen).url).toBe('http://catalog.test:2333/v1/table/acme-silver%24features/query');
	});

	it('passes the upstream status through instead of flattening it to 200', async () => {
		const { response } = await call({
			upstream: () => new Response('{"detail":"nope"}', { status: 403 }),
		});
		expect(response.status).toBe(403);
	});

	it('answers 502 when the upstream cannot be reached', async () => {
		const { response } = await call({
			upstream: () => {
				throw new Error('ECONNREFUSED');
			},
		});
		expect(response.status).toBe(502);
	});

	it('keeps the Arrow content-type, and defaults it when the upstream omits one', async () => {
		const withType = await call({});
		expect(withType.response.headers.get('content-type')).toBe('application/vnd.apache.arrow.file');

		const without = await call({
			upstream: () => new Response(new Uint8Array([1]), { status: 200 }),
		});
		expect(without.response.headers.get('content-type')).toBe('application/vnd.apache.arrow.file');
	});
});
