r"""Submit one RayJob per chunk to k8s/RayJob YAML files or a live Ray cluster.

Two output modes:

  --mode yaml   write .cache/rayjobs/htr-chunk-NNN-of-MMM.yaml for each chunk;
                apply with `kubectl apply -f .cache/rayjobs/`. Uses helpers
                from `control` so entrypoint/name formatting matches the
                live submission path.

  --mode local  delegate to `control.submit_chunk`. Builds an AsyncEngine +
                JobSubmissionClient locally and calls the library.

Usage:
  uv run python scripts/submit_chunks.py --mode yaml
  uv run python scripts/submit_chunks.py --mode local --chunk 0
  uv run python scripts/submit_chunks.py --mode local              # all chunks
"""

from __future__ import annotations

import argparse
import asyncio
import os
import sqlite3
from pathlib import Path

from sqlalchemy import text
from sqlalchemy.ext.asyncio import create_async_engine
from sqlmodel.ext.asyncio.session import AsyncSession

from control import build_entrypoint, chunk_name, submit_chunk


REPO = Path(__file__).resolve().parents[2]
DB_PATH = REPO / ".cache" / "batches.db"
RAYJOB_DIR = REPO / ".cache" / "rayjobs"
DEFAULT_DASHBOARD = "http://localhost:8265"


def _chunks_for_yaml(db: sqlite3.Connection, chunk_id: int | None) -> list[tuple[int, int, list[str]]]:
    """Returns [(chunk_id, chunk_total, [batch_id, ...])]. Sync sqlite — yaml-mode only."""
    if chunk_id is None:
        rows = db.execute(
            "SELECT chunk_id, chunk_total, batch_id FROM batches "
            "WHERE chunk_id IS NOT NULL AND manifest_status='ok' "
            "ORDER BY chunk_id, batch_id"
        ).fetchall()
    else:
        rows = db.execute(
            "SELECT chunk_id, chunk_total, batch_id FROM batches "
            "WHERE chunk_id = ? AND manifest_status='ok' ORDER BY batch_id",
            (chunk_id,),
        ).fetchall()
    grouped: dict[int, tuple[int, list[str]]] = {}
    for cid, ctotal, bid in rows:
        grouped.setdefault(cid, (ctotal, []))[1].append(bid)
    return [(cid, ctotal, bids) for cid, (ctotal, bids) in sorted(grouped.items())]


def _render_yaml(
    chunk_id: int,
    chunk_total: int,
    batch_ids: list[str],
    *,
    cache_bucket: str,
    output: str,
    iiif_url: str,
    pipeline: str,
    image: str,
    cluster_selector: str,
    namespace: str,
) -> str:
    entrypoint = build_entrypoint(
        batch_ids,
        cache_bucket=cache_bucket,
        output=output,
        iiif_url=iiif_url,
        pipeline=pipeline,
    )
    indented_entrypoint = "    " + entrypoint.replace("\n", "\n    ")
    name = chunk_name(chunk_id, chunk_total, pipeline)
    return f"""# Auto-generated by scripts/submit_chunks.py — do not edit by hand.
# chunk_id={chunk_id}, chunk_total={chunk_total}, batches={len(batch_ids)}
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: {name}
  namespace: {namespace}
spec:
  clusterSelector:
    ray.io/cluster: {cluster_selector}
  shutdownAfterJobFinishes: false
  entrypoint: |
{indented_entrypoint}
  runtimeEnvYAML: |
    env_vars:
      HUGGING_FACE_HUB_CACHE: /opt/hf-cache
  submitterPodTemplate:
    spec:
      restartPolicy: Never
      containers:
        - name: submitter
          image: {image}
          envFrom:
            - secretRef:
                name: rask-hcp
"""


async def _chunk_ids_to_submit(session: AsyncSession, chunk_id: int | None) -> list[int]:
    if chunk_id is not None:
        return [chunk_id]
    rows = (
        await session.execute(
            text("SELECT DISTINCT chunk_id FROM batches WHERE chunk_id IS NOT NULL AND manifest_status='ok' ORDER BY chunk_id")
        )
    ).all()
    return [int(r[0]) for r in rows]


async def _run_local(
    db_path: str,
    dashboard_url: str,
    chunk_id: int | None,
    cache_bucket: str,
    output: str,
    iiif_url: str,
    pipeline: str,
) -> None:
    from ray.job_submission import JobSubmissionClient

    engine = create_async_engine(f"sqlite+aiosqlite:///{db_path}")
    try:
        async with AsyncSession(engine, expire_on_commit=False) as session:
            chunk_ids = await _chunk_ids_to_submit(session, chunk_id)
            if not chunk_ids:
                raise SystemExit(f"no chunks found{f' for chunk_id={chunk_id}' if chunk_id is not None else ''}")
            ray_client = JobSubmissionClient(dashboard_url)
            print(f"Submitting {len(chunk_ids)} chunk(s) to {dashboard_url} ...")
            for cid in chunk_ids:
                result = await submit_chunk(
                    session,
                    ray_client,
                    chunk_id=cid,
                    repo_root=REPO,
                    cache_bucket=cache_bucket,
                    output=output,
                    iiif_url=iiif_url,
                    pipeline=pipeline,
                )
                print(f"  chunk {result.chunk_id:>3}/{result.chunk_total} ({len(result.batches)} batches) -> {result.submission_id}")
    finally:
        await engine.dispose()


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=["yaml", "local"], default="yaml")
    ap.add_argument("--chunk", type=int, default=None, help="Single chunk_id; default: all chunks")
    ap.add_argument("--db", default=str(DB_PATH))
    ap.add_argument("--cache-bucket", default="images-batch")
    ap.add_argument("--output", default="s3://images-batch-alto")
    ap.add_argument("--iiif-url", default=os.environ.get("IIIF_URL", "https://iiifintern-ai.ra.se"))
    ap.add_argument("--pipeline", default="htr")
    ap.add_argument("--image", default="ghcr.io/AI-Riksarkivet/ra-batch:0.2.0")
    ap.add_argument("--cluster-selector", default="ai-dev-cluster")
    ap.add_argument("--namespace", default="ai-dev")
    ap.add_argument(
        "--dashboard-url",
        default=os.environ.get("RAY_DASHBOARD_URL", DEFAULT_DASHBOARD),
        help="Ray Dashboard HTTP URL for JobSubmissionClient",
    )
    args = ap.parse_args()

    if args.mode == "yaml":
        db = sqlite3.connect(args.db)
        try:
            chunks = _chunks_for_yaml(db, args.chunk)
        finally:
            db.close()
        if not chunks:
            raise SystemExit(f"no chunks found{f' for chunk_id={args.chunk}' if args.chunk is not None else ''}")
        RAYJOB_DIR.mkdir(parents=True, exist_ok=True)
        for cid, ctotal, batches in chunks:
            yaml = _render_yaml(
                cid,
                ctotal,
                batches,
                cache_bucket=args.cache_bucket,
                output=args.output,
                iiif_url=args.iiif_url,
                pipeline=args.pipeline,
                image=args.image,
                cluster_selector=args.cluster_selector,
                namespace=args.namespace,
            )
            path = RAYJOB_DIR / f"{chunk_name(cid, ctotal, args.pipeline)}.yaml"
            path.write_text(yaml, encoding="utf-8")
        print(f"Wrote {len(chunks)} RayJob manifest(s) to {RAYJOB_DIR}")
        print("Apply with: kubectl apply -f .cache/rayjobs/")
    else:
        asyncio.run(
            _run_local(
                args.db,
                args.dashboard_url,
                args.chunk,
                args.cache_bucket,
                args.output,
                args.iiif_url,
                args.pipeline,
            )
        )


if __name__ == "__main__":
    main()
