r"""Submit one RayJob per chunk to either k8s/RayJob YAML files or a live Ray cluster.

Two output modes:

  --mode yaml   write .cache/rayjobs/htr-chunk-NNN-of-MMM.yaml for each chunk;
                apply with `kubectl apply -f .cache/rayjobs/`. Templated from
                k8s/rayjob-htr.yaml.

  --mode local  submit directly via ray.job_submission.JobSubmissionClient
                against \$RAY_ADDRESS / \$RAY_DASHBOARD_URL (default
                http://localhost:8265). Works once `make ray-up` has been
                run. Returns a submission_id per chunk; the UI's Ray panel
                will pick them up.

Usage:
  uv run python scripts/submit_chunks.py --mode yaml
  uv run python scripts/submit_chunks.py --mode local --chunk 0   # one chunk
  uv run python scripts/submit_chunks.py --mode local             # all chunks
"""

from __future__ import annotations

import argparse
import os
import sqlite3
from datetime import UTC, datetime
from pathlib import Path


REPO = Path(__file__).resolve().parents[2]
DB_PATH = REPO / ".cache" / "batches.db"
RAYJOB_DIR = REPO / ".cache" / "rayjobs"
DEFAULT_DASHBOARD = "http://localhost:8265"


def chunks_with_batches(db: sqlite3.Connection, chunk_id: int | None) -> list[tuple[int, int, list[str]]]:
    """Return [(chunk_id, chunk_total, [batch_id, ...])] for each chunk, sorted by chunk_id."""
    if chunk_id is None:
        rows = db.execute(
            "SELECT chunk_id, chunk_total, batch_id FROM batches WHERE chunk_id IS NOT NULL AND manifest_status='ok' ORDER BY chunk_id, batch_id"
        ).fetchall()
    else:
        rows = db.execute(
            "SELECT chunk_id, chunk_total, batch_id FROM batches WHERE chunk_id = ? AND manifest_status='ok' ORDER BY batch_id",
            (chunk_id,),
        ).fetchall()
    grouped: dict[int, tuple[int, list[str]]] = {}
    for cid, ctotal, bid in rows:
        grouped.setdefault(cid, (ctotal, []))[1].append(bid)
    return [(cid, ctotal, bids) for cid, (ctotal, bids) in sorted(grouped.items())]


def build_entrypoint(
    batch_ids: list[str],
    *,
    cache_bucket: str,
    output: str,
    iiif_url: str,
    pipeline: str,
) -> str:
    """Build a `runner` invocation that processes all batch_ids in one job."""
    parts = [
        "uv run --project projects/runner runner",
        f"--cache-bucket {cache_bucket}",
        f"--output {output}",
        f"--iiif-url {iiif_url}",
        f"--pipeline {pipeline}",
        *(f"--batch {b}" for b in batch_ids),
    ]
    return " \\\n  ".join(parts)


def chunk_name(chunk_id: int, chunk_total: int, pipeline: str = "htr") -> str:
    """Job submission ID. ``htr`` stays unprefixed for backwards compat with
    rows already tagged in batches.db; other pipelines get a ``<name>-`` prefix
    so they don't collide with a future HTR submission for the same chunk."""
    prefix = "htr" if pipeline == "htr" else pipeline
    return f"{prefix}-chunk-{chunk_id:03d}-of-{chunk_total:03d}"


def render_yaml(
    chunk_id: int,
    chunk_total: int,
    batch_ids: list[str],
    *,
    cache_bucket: str,
    output: str,
    iiif_url: str,
    pipeline: str,
    image: str,
    cluster_selector: str,
    namespace: str,
) -> str:
    entrypoint = build_entrypoint(
        batch_ids,
        cache_bucket=cache_bucket,
        output=output,
        iiif_url=iiif_url,
        pipeline=pipeline,
    )
    # Indent each entrypoint line under YAML's | scalar (2-space indent).
    indented_entrypoint = "    " + entrypoint.replace("\n", "\n    ")
    name = chunk_name(chunk_id, chunk_total, pipeline)
    return f"""# Auto-generated by scripts/submit_chunks.py — do not edit by hand.
# chunk_id={chunk_id}, chunk_total={chunk_total}, batches={len(batch_ids)}
apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: {name}
  namespace: {namespace}
spec:
  clusterSelector:
    ray.io/cluster: {cluster_selector}
  shutdownAfterJobFinishes: false
  entrypoint: |
{indented_entrypoint}
  runtimeEnvYAML: |
    env_vars:
      HUGGING_FACE_HUB_CACHE: /opt/hf-cache
  submitterPodTemplate:
    spec:
      restartPolicy: Never
      containers:
        - name: submitter
          image: {image}
          envFrom:
            - secretRef:
                name: rask-hcp
"""


def submit_local(
    chunk_id: int,
    chunk_total: int,
    batch_ids: list[str],
    *,
    cache_bucket: str,
    output: str,
    iiif_url: str,
    pipeline: str,
    dashboard_url: str,
    working_dir: Path,
) -> str:
    """Submit one chunk via ray.job_submission.JobSubmissionClient. Returns submission_id."""
    from ray.job_submission import JobSubmissionClient

    entrypoint = build_entrypoint(
        batch_ids,
        cache_bucket=cache_bucket,
        output=output,
        iiif_url=iiif_url,
        pipeline=pipeline,
    )
    client = JobSubmissionClient(dashboard_url)
    submission_id = client.submit_job(
        entrypoint=entrypoint,
        submission_id=chunk_name(chunk_id, chunk_total, pipeline),
        runtime_env={
            "working_dir": str(working_dir),
            "env_vars": {
                # Pass through MinIO/HCP creds + IIIF endpoint so workers can talk to S3.
                **{k: v for k, v in os.environ.items() if k.startswith(("AWS_", "HCP_", "IIIF_", "RASK_"))},
            },
        },
        metadata={
            "chunk_id": str(chunk_id),
            "chunk_total": str(chunk_total),
            "batches": ",".join(batch_ids),
        },
    )
    return submission_id


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--mode", choices=["yaml", "local"], default="yaml")
    ap.add_argument("--chunk", type=int, default=None, help="Single chunk_id; default: all chunks")
    ap.add_argument("--db", default=str(DB_PATH))
    ap.add_argument("--cache-bucket", default="images-batch")
    ap.add_argument("--output", default="s3://images-batch-alto")
    ap.add_argument("--iiif-url", default=os.environ.get("IIIF_URL", "https://iiifintern-ai.ra.se"))
    ap.add_argument("--pipeline", default="htr")
    # k8s-mode-only knobs
    ap.add_argument("--image", default="ghcr.io/AI-Riksarkivet/ra-batch:0.2.0")
    ap.add_argument("--cluster-selector", default="ai-dev-cluster")
    ap.add_argument("--namespace", default="ai-dev")
    # local-mode-only knob
    ap.add_argument(
        "--dashboard-url",
        default=os.environ.get("RAY_DASHBOARD_URL", DEFAULT_DASHBOARD),
        help="Ray Dashboard HTTP URL for JobSubmissionClient",
    )
    args = ap.parse_args()

    db = sqlite3.connect(args.db)
    chunks = chunks_with_batches(db, args.chunk)
    if not chunks:
        db.close()
        raise SystemExit(f"no chunks found{f' for chunk_id={args.chunk}' if args.chunk is not None else ''}")

    if args.mode == "yaml":
        RAYJOB_DIR.mkdir(parents=True, exist_ok=True)
        for cid, ctotal, batches in chunks:
            yaml = render_yaml(
                cid,
                ctotal,
                batches,
                cache_bucket=args.cache_bucket,
                output=args.output,
                iiif_url=args.iiif_url,
                pipeline=args.pipeline,
                image=args.image,
                cluster_selector=args.cluster_selector,
                namespace=args.namespace,
            )
            path = RAYJOB_DIR / f"{chunk_name(cid, ctotal)}.yaml"
            path.write_text(yaml, encoding="utf-8")
        print(f"Wrote {len(chunks)} RayJob manifest(s) to {RAYJOB_DIR}")
        print("Apply with: kubectl apply -f .cache/rayjobs/")
    else:  # local
        print(f"Submitting {len(chunks)} chunk(s) to {args.dashboard_url} ...")
        now = datetime.now(UTC).isoformat(timespec="seconds")
        for cid, ctotal, batches in chunks:
            sid = submit_local(
                cid,
                ctotal,
                batches,
                cache_bucket=args.cache_bucket,
                output=args.output,
                iiif_url=args.iiif_url,
                pipeline=args.pipeline,
                dashboard_url=args.dashboard_url,
                working_dir=REPO,
            )
            # Record the submission against every batch in this chunk so the
            # viewer can render a "RUNNING" pill on the right rows by joining
            # against /api/ray/jobs. Only tag for htr runs — current_rayjob_id
            # represents transcription progress; prefetch is a precondition,
            # not the work itself, and tagging it would mislead the UI.
            if args.pipeline == "htr":
                db.execute(
                    "UPDATE batches SET current_rayjob_id = ?, current_rayjob_submitted_at = ? WHERE chunk_id = ?",
                    (sid, now, cid),
                )
                db.commit()
            print(f"  chunk {cid:>3}/{ctotal} ({len(batches)} batches) -> {sid}")
    db.close()


if __name__ == "__main__":
    main()
