[project]
name = "core-api-project"
version = "0.1.0"
description = "Deployable: core-api service."
requires-python = ">=3.13"
dependencies = ["core-api", "core[migrations]"]

[tool.uv.sources]
core-api = { workspace = true }
core = { workspace = true }
storage = { workspace = true }
service-kit = { workspace = true }

[tool.uv.workspace]
members = [
    "../../components/services/core_api",
    "../../components/services/core",
    "../../packages/storage",
    "../../packages/service-kit",
    "../../packages/ray-kit",
]
